### PR TITLE
[WIP] tag functions

### PR DESCRIPTION
**Pull request by fenetikm**
Work in progress. 

How is this looking? Just looking for some feedback at this stage.

I think I will change the `add_tag` to `add_tags` so that it supports adding multiple tags that are comma separated. i.e. `vim,script,array`. Might add in an `edit_tags` function as well as an `insert_existing_tag` function.

### CODE REVIEW

**Comment by fiatjaf** [comment]
Great!

`gzt` works good.

For `gzT` the behavior I wanted/expected was that it would search for a list of tags among all existing and add that one. This is the function I would use more, as I don't like to have a large number of tags, but keep reusing the same small number of tags all the time, creating a new one every now and then.

To me the functionality should be:
- `gzt`: creates a new tag and adds it.
- `gzT`: immediately shows the fzf window with all the tags (might keep these in a cached variable built on `refresh_cache`) and adds the one I selected (is there a way to multi-select?)

I don't know about searching a zettel by tag, is that a functionality we want? Maybe it could be added somehow to `gzz/gzi` (if we concatenate the zettel name with strings like `tag:fruit`, for example, then one can search with `gzz` and write `"tag:fruit"` to get all matches for that). I think something like this is enough for searching by tag as it shouldn't be used very often (I also would prefer to not have a new command for searching this as we're approaching command overbloat here, but if you think it is very important and you'll use it all the time, then it's fine).

**Comment by fenetikm** [comment]
Great - thanks for the feedback. Yeah maybe I'll just leave the searching by tag just as a function for now and remove the mapping. I'll get the insert using existing tag going - I am part way through getting that going. I think multi-select should be possible too.

**Comment by fiatjaf** [comment]
I personally don't care much multi-select, so only add it if you feel it is a good idea.

**Comment by fenetikm** [comment]
Closing this in favour of cache PR.

**Comment by fiatjaf** [comment]
https://github.com/fiatjaf/neuron.vim/pull/27

**Pull request closed without merging**
