### PR TITLE
Open backlinks in a split

### PR DESCRIPTION
**Pull request by fenetikm**
Easiest way to see this in action is to open a zettel note, then do `:call neuron#toggle_backlinks()`. That buffer should update as you jump around zettels. I have set it to map to `gzv`. At present that buffer doesn't actually do anything but show you the backlinks. Think that's enough for now?

There are a bunch of config options which I have documented too. Let me know what you think!

### CODE REVIEW

**Comment by fiatjaf** [comment]
Looks great, thank you.

I didn't test it yet (will do later today), but let me ask this: why aren't you using `g:_neuron_backlinks` dictionary which is cached along with the list of all zettels and works well and fast?

**Comment by fenetikm** [comment]
oh right, didn't quite grok what that was for - I'll have a look at using that instead.

**Comment by fiatjaf** [comment]
I also think the `gzt` shortcut should be left to the tags, just because it's `t`. Why did you change it from `gzv`?

I just tested and this is great the way it is though. Let's merge and we can change things later.

**Comment by fenetikm** [comment]
oh I was thinking t for toggle but yeah, can change later. 👍

**Pull request merged**
