### PR TITLE
Address caching issues and directories with special characters

### PR DESCRIPTION
**Pull request by fenetikm**

### CODE REVIEW

**Comment by fiatjaf** [comment]
Is this ready to merge or you're working on it yet?

**Comment by fenetikm** [comment]
@fiatjaf yep, good to go now.

**Comment by fenetikm** [comment]
@fiatjaf not sure if you saw my email elsewhere but I got your request for collab on maintaining this repo but it expired because I was on holiday - if you could please send through again?

**Comment by fenetikm** [comment]
@fiatjaf all good, have accepted the invite now 👍

**Pull request merged**
